CREATE TYPE "IncidentLogEvent" AS ENUM ('INCIDENT_OPENED', 'FAILURE_DETECTED', 'INCIDENT_RESOLVED');

ALTER TABLE "incident_logs"
ADD COLUMN "event" "IncidentLogEvent" NOT NULL DEFAULT 'FAILURE_DETECTED';